[project]
name = "fast-langdetect"
version = "0.1.0"
description = "Quickly detect text language and segment language"
authors = [
    {name = "sudoskys", email = "coldlando@hotmail.com"},
]
dependencies = [
    "fasttext-wheel>=0.9.2",
    "requests>=2.31.0",
    "robust-downloader>=0.0.2",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
package-type = "library"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.4",
]
